# 指定语言环境
language: node_js
# 指定需要sudo权限
# sudo: required
# 指定 node_js 版本
node_js: stable
# 指定缓存模块

install:
  - npm install

cache:
  directories:
    - node_modules

# 指定源码分支
branches:
  only:
    - blog-source

# 执行清缓存，生成网页
script:
  - hexo clean
  - hexo generate

# 设置 git 提交
after_script:
  - cd ./public
  - git init
  - git config user.name "rosescats"
  - git config user.email "qtgate@protonmail.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
global:
  - GH_REF: github.com/rosescats/rosescats.github.io.git
# end: build lifecycle
