language: node_js
node_js: stable
cache:
  directories:
    - node_modules
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "rosescats"
  - git config user.email "qtgate@protonmail.com"
  - git add .
  - git commit -m "travis ci auto build"
  - git push --force --quiet "https://${GIT_REPO_TOKEN}@{GH_REF}" master:master

branches:
  only:
    - blog-source

env:
  global:
    - GH_REF: github.com/rosescats/rosescats.github.io.git
